theme: jekyll-theme-slate
title: Lab 7
description: Create your first GitHub repository, Clone your GitHub repository to your local system, Create lab JavaScript file, and initialize folder as a Node.js folder, Update and commit lab JavaScript file to practice with error handling, Push your changes to GitHub
